name: calling workflow

on: [push]

jobs:
  call-say-hi:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: call say hi
      run: echo "say hi"
      #uses: ./.github/workflows/inputs_workflow.yaml
      #with: 
      # name: Marte
