name: calling workflow

on: [push]

jobs:
  call-say-hi:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: call say hi
      uses: Anubis-1001/gh_actions_practice/.github/workflows/inputs_workflow.yaml@main
      with: 
       name: Marte
