name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: '1.22.5'

    - name: Build go binary
      run: go build ./...

    - name: test
      run: go test -v ./...
